[build]
  publish = "public"
  command = "gatsby build"
  
  
[build.environment]
  NODE_VERSION = "12"

[[plugins]]
package = "@netlify/plugin-gatsby"

[[redirects]]
http://adfreeyoutube.com/* https://adfreeyt.com/:splat 301!
https://adfreeyoutube.com/* https://adfreeyt.com.com/:splat 301!