[build]
  publish = "public"
  command = "gatsby build"
  
  
[build.environment]
  NODE_VERSION = "12"

[[plugins]]
package = "@netlify/plugin-gatsby"

[[redirects]]
  from = "adfreeyoutube.com"
  to = "adfreeyt.com"
  status = 301